config/routes.rb
Rails.application.routes.draw do
  root "items#index"

  resources :categories

  resources :items do 
    resources :comments, only: [:create]
  end

  # users
  get "/login", to: "users#login"
  post "/login", to: "users#sign_in"
  delete "/logout", to: "users#logout"
  get "/sign_up", to: "users#sign_up"
  post "/sign_up", to: "users#registration"

  # APIs
  namespace :api do
    namespace :v1 do
      resources :items, only: [] do
        member do
          post :favorite
        end
      end
    end
  end
end

app/views/shared/_flash.html.erb
<% if notice %>
<div class="alert alert-success" role="alert">
  <%= notice %>
</div>
<% end %> <% if alert %>
<div class="alert alert-danger" role="alert">
  <%= alert %>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <p>&copy; 五倍紅寶石rails訓練中</p>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">訂便當</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "餐點列表", items_path, class: 'nav-link' %>
      </li>

      <% if current_user %>
        <li class="nav-item">
          <%= link_to "我要開團", "#", class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <a href="/sign_up" class="nav-link">註冊</a>
        </li>
        <li class="nav-item">
          <a href="/login" class="nav-link">登入</a>
        </li>
      <% end %>
    </ul>

    <% if current_user %>
    你好，<%= current_user.email  %>
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "登出", logout_path, method: 'delete', class: 'nav-link' %>
      </li>
    </ul>
    <% end %>
  </div>
</nav>
